In [ ]:
import numpy as np

In [ ]:
A = np.random.random((3,3))
B = np.random.random((3,3))
print(A)
print(B)

[[0.30703566 0.54893668 0.61151894]
 [0.84011892 0.57021462 0.25334316]
 [0.35476671 0.36512466 0.9504655 ]]
[[0.32394222 0.14590848 0.63593601]
 [0.60249125 0.22243168 0.31923334]
 [0.00483459 0.47701779 0.29564976]]


In [ ]:
A.T

array([[0.30703566, 0.84011892, 0.35476671],
       [0.54893668, 0.57021462, 0.36512466],
       [0.61151894, 0.25334316, 0.9504655 ]])

In [ ]:
C = np.dot((A.T),A) + B
print(C)

[[1.24987234 0.92303379 1.37372604]
 [1.37961656 0.9822239  1.14641688]
 [0.74262462 1.30420134 1.63717259]]


In [ ]:
D = np.array([[2,3,6,7,4],
              [3,5,7,9,10],
              [6,7,8,9,12]])
print(D)

[[ 2  3  6  7  4]
 [ 3  5  7  9 10]
 [ 6  7  8  9 12]]


In [ ]:
print(D[1:2:,1:2:])

[[5]]


In [ ]:
print(D[-2:-1:,-4:-3:])

[[5]]


In [ ]:
print(D[-2,-4])

5
