## Numpy

In [1]:
import numpy as np

In [39]:
a = np.array([1,2,3])

print(a[1])
a[1] = 5
print(a[1])
print(type(a))
print(a.dtype)

2
5
<class 'numpy.ndarray'>
int32


In [9]:
b = np.array([[1,2,3], [1,2,3]])
type(b)


numpy.ndarray

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [16]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [15]:
b = np.eye((4))
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
a = np.random.random((1,1)) + 1
b = np.random.random((2,1)) + 3
c = np.random.random((2,1)) + 5
print(a)
print(b)
print(c)
d = np.concatenate((b,c),axis=0)
e = np.concatenate((d,a), axis = 0)
e

[[1.82497921]]
[[3.46113161]
 [3.78612762]]
[[5.43858102]
 [5.77200661]]


array([[3.46113161],
       [3.78612762],
       [5.43858102],
       [5.77200661],
       [1.82497921]])

In [21]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
z = np.array([1.2,2.5], dtype=np.int64)

print(x,y,z)
print(x.dtype, y.dtype, z.dtype)

[[1 2]
 [3 4]] [[5 6]] [1 2]
int32 int32 int64


### Array

In [57]:
a = np.array([[1,2,3], [1,2,3]])
b = np.array([[3,2,2], [5,3,3]])

print(np.add(a,b), end = "\n\n")
print(np.subtract(a,b), end = "\n\n")
print(np.multiply(a,b))
print(np.divide(a,b,  dtype = np.float64), end = "\n\n")

[[4 4 5]
 [6 5 6]]

[[-2  0  1]
 [-4 -1  0]]

[[3 4 6]
 [5 6 9]]
[[0.33333333 1.         1.5       ]
 [0.2        0.66666667 1.        ]]



In [69]:
a = np.array([[1,2,3], [1,2,3]])
b = np.array([[3,2,2], [5,3,3]])

print(a)
print(b)
# print(a @ b)

[[1 2 3]
 [1 2 3]]
[[3 2 2]
 [5 3 3]]


In [71]:
a = np.array([[1,2,3], [1,2,3]])
print(a)
print(a.T)

[[1 2 3]
 [1 2 3]]
[[1 1]
 [2 2]
 [3 3]]


In [72]:
a = np.array([[1,2,3], [1,2,3]])
print(np.exp(a))

[[ 2.71828183  7.3890561  20.08553692]
 [ 2.71828183  7.3890561  20.08553692]]


## PyTorch

In [99]:
import torch as tc
print(torch.__version__)

2.0.0+cpu


In [100]:
print(torch.Tensor)

<class 'torch.Tensor'>


In [101]:
x = torch.tensor([[1,1],[1,1]])
x

tensor([[1, 1],
        [1, 1]])

In [102]:
x = torch.rand(2,3)+2
y = torch.rand(2,3)+5

print(torch.cat((x,y),0))

tensor([[2.3389, 2.3378, 2.1263],
        [2.6583, 2.9104, 2.9064],
        [5.2309, 5.0316, 5.1454],
        [5.8696, 5.4144, 5.8279]])


In [103]:
a = np.random.random((2,2))
print(a)
print(type(a))
x = torch.tensor(a)
print(x)
print(type(x))

[[0.57558608 0.30618228]
 [0.00201906 0.02627755]]
<class 'numpy.ndarray'>
tensor([[0.5756, 0.3062],
        [0.0020, 0.0263]], dtype=torch.float64)
<class 'torch.Tensor'>


In [104]:
x = torch.from_numpy(a)
x

tensor([[0.5756, 0.3062],
        [0.0020, 0.0263]], dtype=torch.float64)

In [105]:
x = torch.zeros(2,2)
print(x)

x = torch.ones(2,2)
print(x)

x = torch.eye(5)
print(x)


tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [110]:
x = tc.rand(2,3)+2
y = tc.rand(2,3)+5

print(x)
print(y)
print(x+y)
print(tc.add(x,y))
print(tc.sub(x,y))


tensor([[2.5901, 2.4285, 2.6636],
        [2.5788, 2.9933, 2.9425]])
tensor([[5.0020, 5.9787, 5.0519],
        [5.9953, 5.2229, 5.9462]])
tensor([[7.5921, 8.4072, 7.7154],
        [8.5740, 8.2162, 8.8887]])
tensor([[7.5921, 8.4072, 7.7154],
        [8.5740, 8.2162, 8.8887]])
tensor([[-2.4118, -3.5502, -2.3883],
        [-3.4165, -2.2295, -3.0038]])


In [115]:
x = tc.rand(2,3)
print(x.shape)
print(x.dim())
print(x.type())

torch.Size([2, 3])
2
torch.FloatTensor


In [132]:
x = tc.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(x, end="\n")

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [134]:
print(x[::,0])

tensor([1, 4, 7])


In [129]:
# Every row, only the last column
print(x[::, -1], end='\n')

tensor([3, 6, 9])


In [130]:
print(x[1:3:], end="\n")

tensor([[4, 5, 6],
        [7, 8, 9]])


In [131]:
print(x[-1::], end="\n")

tensor([[7, 8, 9]])


In [151]:
print(x[-2::,-2::])

tensor([[5, 6],
        [8, 9]])


In [177]:
y = tc.tensor([[[1,2,1],[3,4,4]],[[5,6,5],[7,8,2]],
               [[9,10,4],[11,12,15]],[[13,14,34],[15,16,55]]])
print(y.dtype)
print(type(y))
print(y.shape)
print(y)

torch.int64
<class 'torch.Tensor'>
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  1],
         [ 3,  4,  4]],

        [[ 5,  6,  5],
         [ 7,  8,  2]],

        [[ 9, 10,  4],
         [11, 12, 15]],

        [[13, 14, 34],
         [15, 16, 55]]])


In [191]:
# Last 2 rows and 2 columns
print(y[2::,::,1::])

tensor([[[10,  4],
         [12, 15]],

        [[14, 34],
         [16, 55]]])


In [203]:
# Last 1 rows and 2nd column only
print(y[-1::,-1::,1:2:])

tensor([[[16]]])
